# Application pipeline: C/WAT -> Wasm -> wasm2c -> native DPU; native C hosts.
# Discover application directories containing a C or WAT guest.
PRIM_BENCH := $(sort $(notdir $(patsubst %/,%,$(dir $(wildcard examples/prim/*/guest.c examples/prim/*/guest.wat)))))
EXAMPLE_NAMES := $(sort $(notdir $(patsubst %/,%,$(dir $(wildcard examples/*/guest.c examples/*/guest.wat)))) $(PRIM_BENCH))
vpath %/host.c examples examples/prim
vpath %/guest.c examples examples/prim
vpath %/guest.wat examples examples/prim
PIMWASM_GENERATED := imports.c module.c module.h module_dpu.c guest.c guest.h metadata.h manifest.json
PIMWASM_DPU_FLAGS := -O2 -ffp-contract=off -g -std=c11 -fstack-size-section -DNR_TASKLETS=1 -Wall -Wextra -Wno-unused-parameter -Wno-unused-function -Isrc/dpu -Isrc/common -Iinclude
PIMWASM_DPU_SOURCE := $(wildcard src/dpu/*.c)
PIMWASM_DPU_HEADERS := $(wildcard src/dpu/*.h) src/common/wire.h include/pimwasm.h
WASM_FLAGS := --target=wasm32-unknown-unknown -O2 -ffreestanding -fno-vectorize -fno-slp-vectorize -fno-unroll-loops -ffp-contract=off
BUILD_FILES := Makefile make/pimwasm.mk
.PRECIOUS: build/examples/%/guest.o
.PHONY: pimwasm pimwasm-bundle examples prim example
pimwasm: $(foreach name,$(EXAMPLE_NAMES),build/examples/$(name)/dpu) build/libpimwasm.a
prim: $(foreach name,$(PRIM_BENCH),build/examples/$(name)/dpu build/examples/$(name)/host)
# Native example applications use only the public PIMWASM API.
EXAMPLE_HOSTS := $(foreach name,$(EXAMPLE_NAMES),build/examples/$(name)/host)
examples: pimwasm $(EXAMPLE_HOSTS)
build/examples:
	mkdir -p $@
build/examples/%/host: %/host.c examples/support/host.h include/pimwasm.h build/libpimwasm.a $(BUILD_FILES) | build/examples
	mkdir -p $(@D)
	$(CC) $(HOST_FLAGS) -Iinclude $< build/libpimwasm.a $(SDK_FLAGS) -o $@

example:
	@test -n "$(NAME)" && [[ " $(EXAMPLE_NAMES) " == *" $(NAME) "* ]] || { echo 'Set NAME to an example name'; exit 1; }
	$(MAKE) build/examples/$(NAME)/dpu build/examples/$(NAME)/host

# C entry functions match application names; WAT declares its own exports.
# Disable floating-point contraction to preserve separate multiply/add operations.
build/examples/%/guest.o: %/guest.c $(BUILD_FILES)
	mkdir -p $(@D)
	$(WASM_CC) $(WASM_FLAGS) -c $< -o $@
build/examples/%/module.wasm: build/examples/%/guest.o $(BUILD_FILES)
	$(WASM_LD) --no-entry --export=$* --initial-memory=131072 --max-memory=131072 $< -o $@
	wasm-validate $@
build/examples/%/module.wasm: %/guest.wat $(BUILD_FILES)
	mkdir -p $(@D)
	wat2wasm $< -o $@
	wasm-validate $@
define PIMWASM_RULES
$$(addprefix build/examples/$(1)/,$$(PIMWASM_GENERATED)) &: build/examples/$(1)/module.wasm scripts/pimwasm_compile.py scripts/pimwasm_imports.py scripts/pimwasm_exceptions.py $$(BUILD_FILES)
	python3 scripts/pimwasm_compile.py $$< --out build/examples/$(1)
endef
$(foreach name,$(EXAMPLE_NAMES),$(eval $(call PIMWASM_RULES,$(name))))
# These patterns also compile arbitrary accepted bundles generated by pimwasm-bundle.
build/examples/%/dpu: build/examples/%/module_dpu.c build/examples/%/module.h build/examples/%/guest.c build/examples/%/imports.c build/examples/%/guest.h build/examples/%/metadata.h build/examples/%/manifest.json $(PIMWASM_DPU_SOURCE) $(PIMWASM_DPU_HEADERS) scripts/verify_pimwasm_dpu.py $(BUILD_FILES)
	$(DPU_CC) $(PIMWASM_DPU_FLAGS) -DSTACK_SIZE_DEFAULT=4096 -Ibuild/examples/$* $(PIMWASM_DPU_SOURCE) build/examples/$*/module_dpu.c build/examples/$*/guest.c -o $@.unchecked
	python3 scripts/verify_pimwasm_dpu.py $@.unchecked --report build/examples/$*/dpu-resources.json || { rm -f $@.unchecked; exit 1; }
	mv $@.unchecked $@
# Usage: make pimwasm-bundle WASM=/path/input.wasm NAME=my_module
pimwasm-bundle:
	@test -n "$(WASM)" && test -n "$(NAME)" || { echo 'Set WASM and NAME'; exit 1; }
	@python3 -c 'import re,sys; assert re.fullmatch(r"[A-Za-z0-9_]+",sys.argv[1]), "NAME must contain only letters, numbers, underscore"' '$(NAME)'
	python3 scripts/pimwasm_compile.py "$(WASM)" --out "build/examples/$(NAME)" $(if $(IMPORTS),--imports "$(IMPORTS)")
	$(MAKE) "build/examples/$(NAME)/dpu"
build/pimwasm_host.o: src/host/host.c src/common/wire.h include/pimwasm.h $(BUILD_FILES) | build
	$(CC) $(HOST_FLAGS) -Iinclude -Isrc/common $(SDK_FLAGS) -c $< -o $@
build/libpimwasm.a: build/pimwasm_host.o $(BUILD_FILES)
	ar rcs $@ $<
